version: '2'

services:
  agileconnectapi:
    image: user/agileconnectapi
    build:
      context: ./src/AgileConnectApi
      dockerfile: Dockerfile
      args:
        source: ${DOCKER_BUILD_SOURCE}
